# try catch语句

try 中一般都是期望执行的代码

catch 用来处理try中发生的异常     必须要throw  exception吗



> 1.即使try中抛出异常   最终也会执行catch中的抛出异常